version: '3'

services:
  everyfin_backend:
    build: .
    container_name: everyfin_backend
    ports:
      - "7515:7515"
    depends_on:
      - test-mongo
    environment:
      - MONGO_LOCAL_CONN_URL=mongodb://test-mongo:27017/user
    networks:
      - everyfin

  test-mongo:
    image: mongo:latest
    container_name: test-mongo
    volumes:
      - /var/lib/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - everyfin

networks:
  everyfin:
    driver: bridge
