const ERROR_LOGIN_PASSWORD_INVALID = "ERROR_LOGIN_PASSWORD_INVALID";
const ERROR_USER_NOT_VERIFICATION = "ERROR_USER_NOT_VERIFICATION";
const ERROR_EMAIL_TAKEN = "ERROR_EMAIL_TAKEN";
const ERROR_LOGIN_TAKEN = "ERROR_LOGIN_TAKEN";
const ERROR_NO_USER = "ERROR_NO_USER";
const ERROR_TOKEN_INVALID = "ERROR_TOKEN_INVALID";
const ERROR_OLD_PASSWORD_INVALID = "ERROR_OLD_PASSWORD_INVALID";
const ERROR_PASSWORD_NOT_MATCH = "ERROR_PASSWORD_NOT_MATCH";
const ERROR_USER_ALREADY_VERIFIED = "ERROR_USER_ALREADY_VERIFIED";
const ERROR_WRONG_PASSWORD = "ERROR_WRONG_PASSWORD";
const ERROR_WRONG_EMAIL = "ERROR_WRONG_EMAIL";
const ERROR_WRONG_MASTERNODE_ADDRESS = "ERROR_WRONG_MASTERNODE_ADDRESS";
const ERROR_WRONG_ADDRESS = "ERROR_WRONG_ADDRESS";
const ERROR_WRONG_TX_HASH = "ERROR_WRONG_TX_HASH";
const ERROR_TOKEN_LIFETIME_IS_OVER = "ERROR_TOKEN_LIFETIME_IS_OVER";
const INVALID_PASSWORD_RECOVERY_LINK = "INVALID_PASSWORD_RECOVERY_LINK";
const PASSWORD_SUCCESSFULLY_CHANGED = "PASSWORD_SUCCESSFULLY_CHANGED";
const WATCHLIST_ADDRESS_ALREADY_EXIST = "WATCHLIST_ADDRESS_ALREADY_EXIST";
const TX_HASH_ALREADY_EXIST = "TX_HASH_ALREADY_EXIST";
const INVALID_NOTIFICATION_STATUS = "INVALID_NOTIFICATION_STATUS";
const INVALID_NOTIFICATION_DESTINATION = "INVALID_NOTIFICATION_DESTINATION";
const WATCHLIST_ADDRESS_NOT_PROVIDED = "WATCHLIST_ADDRESS_NOT_PROVIDED";
const TX_HASH_NOT_PROVIDED = "TX_HASH_NOT_PROVIDED";
const WATCHLIST_ADDRESS_NOT_FOUND = "WATCHLIST_ADDRESS_NOT_FOUND";
const INVALID_CURRENCY = "INVALID_CURRENCY";
const CURRENCY_NOT_PROVIDED = "CURRENCY_NOT_PROVIDED";
const TX_HASH_NOT_FOUND = "TX_HASH_NOT_FOUND";
const NOTIFY_NOT_FOUND = "NOTIFY_NOT_FOUND";
const COMMENT_NOT_FOUND = "COMMENT_NOT_FOUND";
const COMMENT_NOT_PROVIDED = "COMMENT_NOT_PROVIDED";
const COMMENT_ID_NOT_PROVIDED = "COMMENT_ID_NOT_PROVIDED";
const ERROR_CANNOT_REPLY_TO_REPLY = "ERROR_CANNOT_REPLY_TO_REPLY";
const MISSING_CAPTCHA_DATA = "MISSING_CAPTCHA_DATA";
const CAPTCHA_VALIDATION_ERROR = "CAPTCHA_VALIDATION_ERROR";
const SEND_LIMIT_EXCEEDED = "SEND_LIMIT_EXCEEDED";

const OFF = "OFF";
const ALL = "ALL";
const ONLY_INCOMING = "ONLY_INCOMING";
const ONLY_OUTGOING = "ONLY_OUTGOING";
const INTERNAL = "INTERNAL";
const EMAIL = "EMAIL";
const btcu_testnet = "btcu_testnet";
const btcu = "btcu";

module.exports = {
  ERROR_LOGIN_PASSWORD_INVALID,
  ERROR_USER_NOT_VERIFICATION,
  ERROR_EMAIL_TAKEN,
  ERROR_LOGIN_TAKEN,
  ERROR_NO_USER,
  ERROR_TOKEN_INVALID,
  ERROR_OLD_PASSWORD_INVALID,
  ERROR_PASSWORD_NOT_MATCH,
  ERROR_USER_ALREADY_VERIFIED,
  ERROR_WRONG_PASSWORD,
  ERROR_WRONG_EMAIL,
  INVALID_PASSWORD_RECOVERY_LINK,
  PASSWORD_SUCCESSFULLY_CHANGED,
  ERROR_WRONG_MASTERNODE_ADDRESS,
  ERROR_WRONG_ADDRESS,
  ERROR_WRONG_TX_HASH,
  ERROR_TOKEN_LIFETIME_IS_OVER,
  WATCHLIST_ADDRESS_ALREADY_EXIST,
  TX_HASH_ALREADY_EXIST,
  INVALID_NOTIFICATION_STATUS,
  INVALID_NOTIFICATION_DESTINATION,
  WATCHLIST_ADDRESS_NOT_PROVIDED,
  TX_HASH_NOT_PROVIDED,
  WATCHLIST_ADDRESS_NOT_FOUND,
  INVALID_CURRENCY,
  CURRENCY_NOT_PROVIDED,
  TX_HASH_NOT_FOUND,
  COMMENT_NOT_FOUND,
  COMMENT_NOT_PROVIDED,
  COMMENT_ID_NOT_PROVIDED,
  ERROR_CANNOT_REPLY_TO_REPLY,
  MISSING_CAPTCHA_DATA,
  CAPTCHA_VALIDATION_ERROR,   
  NOTIFY_NOT_FOUND,
  SEND_LIMIT_EXCEEDED,
  OFF,
  ALL,
  ONLY_INCOMING,
  ONLY_OUTGOING,
  INTERNAL,
  EMAIL,
  btcu_testnet,
  btcu,
};
